# GitHub Pages Configuration
theme: jekyll-theme-cayman

# Site settings
title: Francisco Zavala
description: Undergraduate Biomedical Engineering Student | Robotics & Software Developer
url: https://patxi2004.github.io/Curriculumvitae

# Show or hide the title
show_downloads: false